package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private int albumId;
     private Artista artista;
     private Editora editora;
     private String nome;
     private Blob capa;
     private String produtor;
     private String linkAlbum;
     private String ano;
     private Set<Musica> musicas = new HashSet<Musica>(0);

    public Album() {
    }
	
    public Album(int albumId, String nome) {
        this.albumId = albumId;
        this.nome = nome;
    }
    public Album(int albumId, Artista artista, Editora editora, String nome, Blob capa, String produtor, String linkAlbum, String ano, Set<Musica> musicas) {
       this.albumId = albumId;
       this.artista = artista;
       this.editora = editora;
       this.nome = nome;
       this.capa = capa;
       this.produtor = produtor;
       this.linkAlbum = linkAlbum;
       this.ano = ano;
       this.musicas = musicas;
    }
   
    public int getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(int albumId) {
        this.albumId = albumId;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public Editora getEditora() {
        return this.editora;
    }
    
    public void setEditora(Editora editora) {
        this.editora = editora;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Blob getCapa() {
        return this.capa;
    }
    
    public void setCapa(Blob capa) {
        this.capa = capa;
    }
    public String getProdutor() {
        return this.produtor;
    }
    
    public void setProdutor(String produtor) {
        this.produtor = produtor;
    }
    public String getLinkAlbum() {
        return this.linkAlbum;
    }
    
    public void setLinkAlbum(String linkAlbum) {
        this.linkAlbum = linkAlbum;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public Set<Musica> getMusicas() {
        return this.musicas;
    }
    
    public void setMusicas(Set<Musica> musicas) {
        this.musicas = musicas;
    }




}


