package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private int artistaId;
     private String nomeCompleto;
     private String nomeArtista;
     private Date dataNascimento;
     private String nacionalidade;
     private String contacto;
     private Set<Album> albums = new HashSet<Album>(0);

    public Artista() {
    }

    public Artista(int artistaId, String nomeCompleto, String nomeArtista, Date dataNascimento, String nacionalidade, String contacto) {
        this.artistaId = artistaId;
        this.nomeCompleto = nomeCompleto;
        this.nomeArtista = nomeArtista;
        this.dataNascimento = dataNascimento;
        this.nacionalidade = nacionalidade;
        this.contacto = contacto;
    }
	
      
                    
    public Artista(int artistaId, String nomeCompleto, Date dataNascimento) {
        this.artistaId = artistaId;
        this.nomeCompleto = nomeCompleto;
        this.dataNascimento = dataNascimento;
    }
    public Artista(int artistaId, String nomeCompleto, String nomeArtista, Date dataNascimento, String nacionalidade, String contacto, Set<Album> albums) {
       this.artistaId = artistaId;
       this.nomeCompleto = nomeCompleto;
       this.nomeArtista = nomeArtista;
       this.dataNascimento = dataNascimento;
       this.nacionalidade = nacionalidade;
       this.contacto = contacto;
       this.albums = albums;
    }
   
    public int getArtistaId() {
        return this.artistaId;
    }
    
    public void setArtistaId(int artistaId) {
        this.artistaId = artistaId;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getNomeArtista() {
        return this.nomeArtista;
    }
    
    public void setNomeArtista(String nomeArtista) {
        this.nomeArtista = nomeArtista;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }




}


