package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Editora generated by hbm2java
 */
public class Editora  implements java.io.Serializable {


     private int editoraId;
     private String nome;
     private String morada;
     private String contacto;
     private Set<Album> albums = new HashSet<Album>(0);

    public Editora() {
    }

    public Editora(int editoraId, String nome, String morada, String contacto) {
        this.editoraId = editoraId;
        this.nome = nome;
        this.morada = morada;
        this.contacto = contacto;
    }

    
	
    public Editora(int editoraId, String nome, String morada) {
        this.editoraId = editoraId;
        this.nome = nome;
        this.morada = morada;
    }
    public Editora(int editoraId, String nome, String morada, String contacto, Set<Album> albums) {
       this.editoraId = editoraId;
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
       this.albums = albums;
    }
   
    public int getEditoraId() {
        return this.editoraId;
    }
    
    public void setEditoraId(int editoraId) {
        this.editoraId = editoraId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }




}


