package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudio generated by hbm2java
 */
public class Estudio  implements java.io.Serializable {


     private int estudioId;
     private DirEstudio dirEstudio;
     private String morada;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Estudio() {
    }

	
    public Estudio(int estudioId, String morada) {
        this.estudioId = estudioId;
        this.morada = morada;
    }
    public Estudio(int estudioId, DirEstudio dirEstudio, String morada, Set<Reserva> reservas) {
       this.estudioId = estudioId;
       this.dirEstudio = dirEstudio;
       this.morada = morada;
       this.reservas = reservas;
    }
   
    public int getEstudioId() {
        return this.estudioId;
    }
    
    public void setEstudioId(int estudioId) {
        this.estudioId = estudioId;
    }
    public DirEstudio getDirEstudio() {
        return this.dirEstudio;
    }
    
    public void setDirEstudio(DirEstudio dirEstudio) {
        this.dirEstudio = dirEstudio;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


