package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * Instrumental generated by hbm2java
 */
public class Instrumental  implements java.io.Serializable {


     private int instrumentalId;
     private Blob audio;
     private String compositor;

    public Instrumental() {
    }

	
    public Instrumental(int instrumentalId, Blob audio) {
        this.instrumentalId = instrumentalId;
        this.audio = audio;
    }
    public Instrumental(int instrumentalId, Blob audio, String compositor) {
       this.instrumentalId = instrumentalId;
       this.audio = audio;
       this.compositor = compositor;
    }
   
    public int getInstrumentalId() {
        return this.instrumentalId;
    }
    
    public void setInstrumentalId(int instrumentalId) {
        this.instrumentalId = instrumentalId;
    }
    public Blob getAudio() {
        return this.audio;
    }
    
    public void setAudio(Blob audio) {
        this.audio = audio;
    }
    public String getCompositor() {
        return this.compositor;
    }
    
    public void setCompositor(String compositor) {
        this.compositor = compositor;
    }




}


