package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int reservaId;
     private Utilizador utilizador;
     private Estudio estudio;
     private Date dataReserva;
     private char isconfirmed;
     private char isactive;

    public Reserva() {
    }

	
    public Reserva(int reservaId, Date dataReserva, char isconfirmed, char isactive) {
        this.reservaId = reservaId;
        this.dataReserva = dataReserva;
        this.isconfirmed = isconfirmed;
        this.isactive = isactive;
    }
    public Reserva(int reservaId, Utilizador utilizador, Estudio estudio, Date dataReserva, char isconfirmed, char isactive) {
       this.reservaId = reservaId;
       this.utilizador = utilizador;
       this.estudio = estudio;
       this.dataReserva = dataReserva;
       this.isconfirmed = isconfirmed;
       this.isactive = isactive;
    }

    public Reserva(Utilizador utilizador, Estudio estudio, Date dataReserva) {
        this.utilizador = utilizador;
        this.estudio = estudio;
        this.dataReserva = dataReserva;
    }

    public Reserva(Date dataReserva, Estudio estudio, char isconfirmed, char isactive) {
        this.dataReserva = dataReserva;
        this.estudio = estudio;
        this.isconfirmed = isconfirmed;
        this.isactive = isactive;
    }
    
    
    
    
   
    public int getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(int reservaId) {
        this.reservaId = reservaId;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public Estudio getEstudio() {
        return this.estudio;
    }
    
    public void setEstudio(Estudio estudio) {
        this.estudio = estudio;
    }
    public Date getDataReserva() {
        return this.dataReserva;
    }
    
    public void setDataReserva(Date dataReserva) {
        this.dataReserva = dataReserva;
    }
    public char getIsconfirmed() {
        return this.isconfirmed;
    }
    
    public void setIsconfirmed(char isconfirmed) {
        this.isconfirmed = isconfirmed;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }




}


