package classes;
// Generated 13/jun/2018 18:32:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private int utilizadorId;
     private String email;
     private String passwordU;
     private String tipo;
     private Set<Musica> musicas = new HashSet<Musica>(0);
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Utilizador() {
    }

	
    public Utilizador(int utilizadorId, String email, String passwordU, String tipo) {
        this.utilizadorId = utilizadorId;
        this.email = email;
        this.passwordU = passwordU;
        this.tipo = tipo;
    }
    public Utilizador(int utilizadorId, String email, String passwordU, String tipo, Set<Musica> musicas, Set<Reserva> reservas) {
       this.utilizadorId = utilizadorId;
       this.email = email;
       this.passwordU = passwordU;
       this.tipo = tipo;
       this.musicas = musicas;
       this.reservas = reservas;
    }

    public Utilizador(String email, String passwordU, String tipo) {
        this.email = email;
        this.passwordU = passwordU;
        this.tipo = tipo;
    }
    
    
   
    public int getUtilizadorId() {
        return this.utilizadorId;
    }
    
    public void setUtilizadorId(int utilizadorId) {
        this.utilizadorId = utilizadorId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPasswordU() {
        return this.passwordU;
    }
    
    public void setPasswordU(String passwordU) {
        this.passwordU = passwordU;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Musica> getMusicas() {
        return this.musicas;
    }
    
    public void setMusicas(Set<Musica> musicas) {
        this.musicas = musicas;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


